import type { Competitor } from "./types";

export const COMPETITORS: Competitor[] = [
  {
    id: "rdstation",
    name: "RD Station",
    domain: "rdstation.com",
    category: "CRM + Marketing",
    color: "var(--via-util-1)",
    favicon: "R",
    monitoring: true,
    traffic: 4_820_000,
    trafficDelta: -3.2,
    seoKeywords: 18420,
    seoDelta: +1.4,
    pricingTier: "R$ 79–349/mês",
    lastChange: "2h atrás",
    changeType: "pricing",
    changeSummary: 'Novo plano "RD Pro" a R$ 199/mês com IA generativa',
    changeSeverity: "high",
    description:
      "Plataforma brasileira líder em CRM + automação de marketing.",
    health: 92,
    trafficSeries: [4520, 4610, 4720, 4880, 4950, 4900, 4820],
    keywordsTop: [
      "crm para vendas",
      "automação de marketing",
      "funil de vendas",
      "lead scoring",
    ],
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    domain: "pipedrive.com",
    category: "CRM",
    color: "var(--via-util-2)",
    favicon: "P",
    monitoring: true,
    traffic: 8_140_000,
    trafficDelta: +5.7,
    seoKeywords: 24310,
    seoDelta: +2.8,
    pricingTier: "US$ 14–99/mês",
    lastChange: "5h atrás",
    changeType: "feature",
    changeSummary: 'Lançou "AI Sales Assistant" no plano Professional',
    changeSeverity: "high",
    description: "CRM internacional focado em pipeline visual e simplicidade.",
    health: 88,
    trafficSeries: [7400, 7520, 7680, 7820, 7950, 8050, 8140],
    keywordsTop: [
      "pipeline crm",
      "sales crm",
      "crm software",
      "lead management",
    ],
  },
  {
    id: "hubspot",
    name: "HubSpot",
    domain: "hubspot.com",
    category: "CRM + Suite",
    color: "var(--via-util-3)",
    favicon: "H",
    monitoring: true,
    traffic: 42_300_000,
    trafficDelta: +1.1,
    seoKeywords: 184500,
    seoDelta: -0.4,
    pricingTier: "US$ 0–1.500/mês",
    lastChange: "1d atrás",
    changeType: "copy",
    changeSummary:
      'Reposicionou home: "Customer Platform" → "AI-Powered Customer Platform"',
    changeSeverity: "medium",
    description:
      "Suite completa: CRM, marketing, vendas, atendimento e CMS.",
    health: 96,
    trafficSeries: [41200, 41600, 42100, 42400, 42600, 42500, 42300],
    keywordsTop: [
      "crm",
      "inbound marketing",
      "marketing automation",
      "sales hub",
    ],
  },
  {
    id: "ploomes",
    name: "Ploomes",
    domain: "ploomes.com",
    category: "CRM",
    color: "var(--via-util-5)",
    favicon: "Pl",
    monitoring: true,
    traffic: 612_000,
    trafficDelta: +12.4,
    seoKeywords: 4820,
    seoDelta: +6.1,
    pricingTier: "R$ 49–229/mês",
    lastChange: "4h atrás",
    changeType: "feature",
    changeSummary:
      "Adicionou módulo de Propostas com assinatura digital nativa",
    changeSeverity: "medium",
    description:
      "CRM brasileiro forte em vendas complexas B2B e propostas.",
    health: 81,
    trafficSeries: [510, 528, 545, 562, 580, 598, 612],
    keywordsTop: [
      "crm b2b",
      "crm vendas complexas",
      "proposta comercial",
      "gestão de funil",
    ],
  },
  {
    id: "agendor",
    name: "Agendor",
    domain: "agendor.com.br",
    category: "CRM",
    color: "var(--via-util-6)",
    favicon: "A",
    monitoring: true,
    traffic: 384_000,
    trafficDelta: -1.8,
    seoKeywords: 3210,
    seoDelta: +0.7,
    pricingTier: "R$ 0–129/mês",
    lastChange: "3d atrás",
    changeType: "pricing",
    changeSummary: "Reduziu preço do plano Pro de R$ 149 para R$ 129",
    changeSeverity: "low",
    description:
      "CRM brasileiro voltado a PMEs com foco em simplicidade.",
    health: 74,
    trafficSeries: [395, 392, 388, 390, 386, 388, 384],
    keywordsTop: [
      "crm gratuito",
      "crm pme",
      "gestão de clientes",
      "crm simples",
    ],
  },
];
