/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSwotRouteImport } from './routes/_authed/swot'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedOnboardRouteImport } from './routes/_authed/onboard'
import { Route as AuthedHelpRouteImport } from './routes/_authed/help'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCompareRouteImport } from './routes/_authed/compare'
import { Route as AuthedAlertsRouteImport } from './routes/_authed/alerts'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings.index'
import { Route as AuthedCompetitorsIndexRouteImport } from './routes/_authed/competitors.index'
import { Route as AuthedSettingsIntegrationsRouteImport } from './routes/_authed/settings.integrations'
import { Route as AuthedSettingsEquipeRouteImport } from './routes/_authed/settings.equipe'
import { Route as AuthedCompetitorsIdRouteImport } from './routes/_authed/competitors.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSwotRoute = AuthedSwotRouteImport.update({
  id: '/swot',
  path: '/swot',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardRoute = AuthedOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHelpRoute = AuthedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompareRoute = AuthedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAlertsRoute = AuthedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedCompetitorsIndexRoute = AuthedCompetitorsIndexRouteImport.update({
  id: '/competitors/',
  path: '/competitors/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIntegrationsRoute =
  AuthedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsEquipeRoute = AuthedSettingsEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedCompetitorsIdRoute = AuthedCompetitorsIdRouteImport.update({
  id: '/competitors/$id',
  path: '/competitors/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convite': typeof ConviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AuthedAlertsRoute
  '/compare': typeof AuthedCompareRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/help': typeof AuthedHelpRoute
  '/onboard': typeof AuthedOnboardRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/swot': typeof AuthedSwotRoute
  '/competitors/$id': typeof AuthedCompetitorsIdRoute
  '/settings/equipe': typeof AuthedSettingsEquipeRoute
  '/settings/integrations': typeof AuthedSettingsIntegrationsRoute
  '/competitors/': typeof AuthedCompetitorsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convite': typeof ConviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AuthedAlertsRoute
  '/compare': typeof AuthedCompareRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/help': typeof AuthedHelpRoute
  '/onboard': typeof AuthedOnboardRoute
  '/swot': typeof AuthedSwotRoute
  '/competitors/$id': typeof AuthedCompetitorsIdRoute
  '/settings/equipe': typeof AuthedSettingsEquipeRoute
  '/settings/integrations': typeof AuthedSettingsIntegrationsRoute
  '/competitors': typeof AuthedCompetitorsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/convite': typeof ConviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/alerts': typeof AuthedAlertsRoute
  '/_authed/compare': typeof AuthedCompareRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/help': typeof AuthedHelpRoute
  '/_authed/onboard': typeof AuthedOnboardRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/swot': typeof AuthedSwotRoute
  '/_authed/competitors/$id': typeof AuthedCompetitorsIdRoute
  '/_authed/settings/equipe': typeof AuthedSettingsEquipeRoute
  '/_authed/settings/integrations': typeof AuthedSettingsIntegrationsRoute
  '/_authed/competitors/': typeof AuthedCompetitorsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convite'
    | '/login'
    | '/signup'
    | '/alerts'
    | '/compare'
    | '/dashboard'
    | '/help'
    | '/onboard'
    | '/settings'
    | '/swot'
    | '/competitors/$id'
    | '/settings/equipe'
    | '/settings/integrations'
    | '/competitors/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convite'
    | '/login'
    | '/signup'
    | '/alerts'
    | '/compare'
    | '/dashboard'
    | '/help'
    | '/onboard'
    | '/swot'
    | '/competitors/$id'
    | '/settings/equipe'
    | '/settings/integrations'
    | '/competitors'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/convite'
    | '/login'
    | '/signup'
    | '/_authed/alerts'
    | '/_authed/compare'
    | '/_authed/dashboard'
    | '/_authed/help'
    | '/_authed/onboard'
    | '/_authed/settings'
    | '/_authed/swot'
    | '/_authed/competitors/$id'
    | '/_authed/settings/equipe'
    | '/_authed/settings/integrations'
    | '/_authed/competitors/'
    | '/_authed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ConviteRoute: typeof ConviteRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/swot': {
      id: '/_authed/swot'
      path: '/swot'
      fullPath: '/swot'
      preLoaderRoute: typeof AuthedSwotRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboard': {
      id: '/_authed/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof AuthedOnboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/help': {
      id: '/_authed/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthedHelpRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/compare': {
      id: '/_authed/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthedCompareRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/alerts': {
      id: '/_authed/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthedAlertsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/competitors/': {
      id: '/_authed/competitors/'
      path: '/competitors'
      fullPath: '/competitors/'
      preLoaderRoute: typeof AuthedCompetitorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/integrations': {
      id: '/_authed/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/equipe': {
      id: '/_authed/settings/equipe'
      path: '/equipe'
      fullPath: '/settings/equipe'
      preLoaderRoute: typeof AuthedSettingsEquipeRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/competitors/$id': {
      id: '/_authed/competitors/$id'
      path: '/competitors/$id'
      fullPath: '/competitors/$id'
      preLoaderRoute: typeof AuthedCompetitorsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedSettingsRouteChildren {
  AuthedSettingsEquipeRoute: typeof AuthedSettingsEquipeRoute
  AuthedSettingsIntegrationsRoute: typeof AuthedSettingsIntegrationsRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsEquipeRoute: AuthedSettingsEquipeRoute,
  AuthedSettingsIntegrationsRoute: AuthedSettingsIntegrationsRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAlertsRoute: typeof AuthedAlertsRoute
  AuthedCompareRoute: typeof AuthedCompareRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedHelpRoute: typeof AuthedHelpRoute
  AuthedOnboardRoute: typeof AuthedOnboardRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedSwotRoute: typeof AuthedSwotRoute
  AuthedCompetitorsIdRoute: typeof AuthedCompetitorsIdRoute
  AuthedCompetitorsIndexRoute: typeof AuthedCompetitorsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAlertsRoute: AuthedAlertsRoute,
  AuthedCompareRoute: AuthedCompareRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedHelpRoute: AuthedHelpRoute,
  AuthedOnboardRoute: AuthedOnboardRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedSwotRoute: AuthedSwotRoute,
  AuthedCompetitorsIdRoute: AuthedCompetitorsIdRoute,
  AuthedCompetitorsIndexRoute: AuthedCompetitorsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ConviteRoute: ConviteRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
